# Generated by Django 5.1 on 2024-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_hotelinformation_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinformation',
            name='description',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('image', 'hotel')},
        ),
    ]
