# Generated by Django 5.1 on 2024-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_hotelinformation_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='images',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='description',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='roomType',
            field=models.CharField(default='Single', max_length=400),
        ),
    ]
