# Generated by Django 5.1 on 2024-08-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_images_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinformation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotelinformation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hotelinformation',
            name='roomType',
        ),
    ]
