# Generated by Django 5.1 on 2024-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_amenities_hotels_remove_location_hotels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
