# Generated by Django 5.1 on 2024-08-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_amenities_name_alter_hotelinformation_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinformation',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
