# Generated by Django 5.1 on 2024-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_hotelinformation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
