# Generated by Django 5.1 on 2024-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_amenities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelinformation',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='polls.amenities'),
        ),
    ]
